name: ai_cleaner
description: "AI Cleaner & Privacy Shield App developed by Renante Fullo"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# Gagamitin nito ang apk_icon.png na nasa root folder mo
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "apk_icon.png"

flutter:
  uses-material-design: true
  assets:
    - apk_icon.png
